name: Build

on:
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    container: thomasweise/texlive
    name: Build CV
    env:
      ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          apt-get update && apt-get install -y fonts-font-awesome
          fmtutil-sys --all 1> /dev/null || true
          tlmgr init-usertree
          tlmgr install fontawesome
          xelatex cv.tex
